version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mental_health_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db  

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mental_health_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASSWORD: example
      DB_PORT: 27017
      NODE_ENV: ${NODE_ENV}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - .:/home/node/app 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo_data:  
