name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          MAIL_USERNAME=${{secrets.MAIL_USERNAME}} \
          MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} \
          NODE_ENV=testing \
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
            docker-compose run \
              -e MAIL_USERNAME=${{secrets.MAIL_USERNAME}} \
              -e MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} \
              -e NODE_ENV=testing \
              express-app npm install
  
      - name: Run Tests
        run: |
            docker-compose run \
              -e MAIL_USERNAME=${{secrets.MAIL_USERNAME}} \
              -e MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} \
              -e NODE_ENV=testing \
              express-app npm test
