name: CI/CD Pipeline

on: workflow_dispatch

jobs:
  Tests:
    runs-on: ubuntu-latest

    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      NODE_ENV: testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
          docker-compose run express-app npm install
  
      - name: Run Tests
        run: |
          docker-compose run express-app npm test
