name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  Tests:
    runs-on: ubuntu-22.04

    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      NODE_ENV: testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
          docker-compose run express-app npm install
  
      - name: Run Tests
        run: |
          docker-compose run express-app npm test

  Terraform-Setup:
    runs-on: ubuntu-22.04
    needs: Tests
    if: success()
    defaults:
      run:
        working-directory: iac/terraform

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Set up Terraform
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=secrets.tfvars -input=false

      - name: Apply Terraform
        run: terraform apply -var-file=secrets.tfvars -input=false -auto-approve
