name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
          docker-compose run express-app npm install
  
      - name: Run Tests
        id: run_tests
        run: |
          docker-compose run express-app npm test 

  Notify:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract committer's email
        id: extract_email
        run: |
          EMAIL=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r '.commit.author.email')
          echo $EMAIL

      - name: Send email notification on test failure
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: "smtp://${{secrets.MAIL_USERNAME}}:${{secrets.MAIL_PASSWORD}}@smtp.gmail.com:587"
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Tests failed in ${GITHUB_REPOSITORY}"
          from: Nimisha G J
          body: "Tests failed for the repository: ${GITHUB_REPOSITORY}. Please check the workflow for more details."
