name: Test on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Check if tests failed
        run: |
          if [ ${{ job.status }} != 'success' ]; then
            echo "Tests failed. Rolling back commit..."
            git reset --hard HEAD~1
            git push --force
            echo "Commit rolled back successfully."
          fi