name: Test on Push

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
          docker-compose run express-app npm install
  
      - name: Run Tests
        id: run_tests
        run: |
          docker-compose run express-app npm test 
          
  echos:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract committer's email
        id: extract_email
        run: |
          echo ${{ github.repository }}
          echo ${{ github.sha }}
          COMITTER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r '.commit.author.email')
          echo "${{ github.event_name }}=${COMITTER_EMAIL}" >> $GITHUB_OUTPUT

      - name: Send email notification on failure
        if: failure()
        run: |
          EMAIL=$(cat $GITHUB_OUTPUT | grep push | cut -d '=' -f 2)
          echo "Your workflow failed on branch ${{ github.ref }} at commit ${{ github.sha }}. Please check the workflow logs for details." | mail -s "Workflow Failed" $EMAIL

