name: Test on Push

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Images
        run: |
          docker-compose build
        
      - name: Install Node.js Dependencies
        run: |
          docker-compose run express-app npm install
  

      - name: Check if Tests Failed
        run: |
          docker-compose run express-app npm test
          echo "Check"
          echo $?
          if [ $? -ne 0 ]; then
            COMMIT_HASH=$(git rev-parse HEAD)
            echo "Tests failed. Rolling back commit ${COMMIT_HASH}..."
            git reset --hard HEAD~1
            git push --force
            echo "Commit ${COMMIT_HASH} rolled back successfully."
          fi
        continue-on-error: true
